# Bar Chart - Exp Per Capita SQL
# select N.ST, POPULATION, REGION_NAME, EXPENDITURES, 1000000*EXPENDITURES / POPULATION AS "HC_EXP_PER_CAPITA from (select STATE_NAME as "ST", SUM(Y2009) as "EXPENDITURES", REGION_NAME from NHCE where STATE_NAME is not null group by STATE_NAME, REGION_NAME) N inner join (select "STATE" as "ST", AVG(NINE) as "POPULATION" from STATE_POP group by "STATE") S ON N.ST = S.ST;

# Crosstab - Average Exp Growth SQL
# select CODE, ITEM, STATE_NAME, AVERAGE_ANNUAL_PERCENT_GROWTH, FLOOR(AVERAGE_ANNUAL_PERCENT_GROWTH / 7) AS LO, FLOOR(AVERAGE_ANNUAL_PERCENT_GROWTH / 10) AS MED, FLOOR(AVERAGE_ANNUAL_PERCENT_GROWTH / 7) + FLOOR(AVERAGE_ANNUAL_PERCENT_GROWTH / 10) AS HI from NHCE where CODE != '12' and STATE_NAME is not null;